[package]
name = "arbutus"
description = "Arbutus Trees"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
tracing = "0.1.40"
tracing-test = "0.2.5"
